services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/erp_assurance_db
      SPRING_DATASOURCE_USERNAME: erp_user
      SPRING_DATASOURCE_PASSWORD: erp_password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - erp-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: erp_assurance_db
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - erp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - erp-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - erp-network

volumes:
  db_data:

networks:
  erp-network:
