spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_assurance_db
    username: erp_user
    password: erp_password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.erp.assurance.tunisie: DEBUG
    org.springframework.security: DEBUG
